/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant Software (64-bit) 1.1.0.165.1
    Soft IP Version: 1.0.1
    Sun Aug 25 16:46:26 2019
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll (ref_clk_i, rst_n_i, outcore_o, outglobal_o, outcoreb_o,
    outglobalb_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  rst_n_i;
    output  outcore_o;
    output  outglobal_o;
    output  outcoreb_o;
    output  outglobalb_o;
endmodule